config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :plays
  root 'plays#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :plays
end

app/models/play.rb
class Play < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :plays
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController

	before_action :find_play, only: [:show, :edit, :update, :destroy]
	
	def index
		if params[:category].blank?
			@plays = Play.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@plays = Play.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def show
	
	end

	def new
		@play = current_user.plays.build
		@categories = Category.all.map{ |c| [c.name, c.id]}
	end

	def create
		@play = current_user.plays.build(play_params)
		@play.category_id = params[:category_id]

		if @play.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id]}
	end

	def update
		@play.category_id = params[:category_id]

		if @play.update(play_params)
			redirect_to play_path(@play)
		else
			render 'edit'
		end
	end

	def destroy
		@play.destroy
		redirect_to root_path
	end

	private

	def play_params
		params.require(:play).permit(:title, :description, :director, :category_id)
	end

	def find_play
		@play = Play.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Broadway</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar navbar-default">
			<div class="container">
				<div class="navbar-header">
					<%= link_to "Broadway", root_path, class: "navbar-brand" %>
				</div>

				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
					<% else %>
						<li><%= link_to "Sign Up", new_user_registration_path %></li>
						<li><%= link_to "Log In", new_user_session_path %></li>
					<% end %>
				</ul>

				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role='button' aria-expanded="false">Sort <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<% Category.all.each do |category| %>
								<li class="<%= 'active' if params[:category] == category.name %>">
									<%= link_to category.name, plays_path(category: category.name), class: "link" %>
								</li>
							<% end %>
						</ul>
					</li>

					<% if user_signed_in? %>
						<li><%= link_to "Add Play", new_play_path %></li>
					<% end %>
				</ul>
			</div>
		</nav>

		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/plays/_form.html.erb
<%= simple_form_for @play do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  <%= f.input :title, label: "Play Title" %>
  <%= f.input :description %>
  <%= f.input :director %>
  <%= f.button :submit %>
<% end %>

app/views/plays/edit.html.erb
<h1>Edit Broadway Play</h1>

<%= simple_form_for @play, html: {multipart: true} do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.input :title, label: "Play Title" %>
  <%= f.input :description %>
  <%= f.input :director %>
  <%= f.button :submit %>
<% end %>

app/views/plays/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @plays.count == 0 %>
	<h3>There are no plays in this category</h3>
<% else %>
	<% @plays.each do |play| %>
		<h2><%= link_to play.title, play_path(play) %></h2>
	<% end %>
<% end %>

app/views/plays/new.html.erb
<h1>New Broadway Play</h1>

<%= render 'form' %>

app/views/plays/show.html.erb
<h2><%= @play.title %></h2>
<h3><%= @play.director %></h3>
<h4><%= @play.category.name %></h4>
<p><%= @play.description %></p>

<div class="links btn-group">
	<% if user_signed_in? %>
		<% if @play.user_id == current_user.id %>
			<%= link_to "Edit", edit_play_path(@play) %>
			<%= link_to "Delete", play_path(@play), method: :delete, data: { confirm: "Are you sure?"} %>
		<% end %>
	<%  end%>
</div>